## Execute Log In
POST http://localhost:3001/api/sessions HTTP/1.1
content-type: application/json

{
  "username": "riccardo@test.com",
  "password": "prova"
}
###

## Checking if user is still logged-in and get the fill list of pages
GET http://localhost:3001/api/sessions/current HTTP/1.1
###

## Execute Log Out.
DELETE http://localhost:3001/api/sessions/current HTTP/1.1
###

## get all the pages that are published
GET http://localhost:3001/api/pages HTTP/1.1
###

## get a specific page specifing its {id} if the user is logged-in
GET http://localhost:3001/api/pages/1 HTTP/1.1
###

## Create new page if the user is logged-in
POST http://localhost:3001/api/pages HTTP/1.1
content-type: application/json

{
    "title": "prova",
    "creationDate": "2023-06-13",
    "publicationDate": "2023-06-13",
    "blocks": [
      {
        "blockType": "Header",
        "content": "prova header",
        "order": 1
      },
      {
        "blockType": "Paragrafo",
        "content": "prova paragrafo",
        "order": 2
      }
    ]
}
###

## modifica una pagina se l'utente è loggato
PUT http://localhost:3001/api/pages/1 HTTP/1.1
content-type: application/json

{
  "id": 1,
  "title": "prova modifica",
  "authorId": 1,
  "creationDate": "2023-06-13",
  "publicationDate": "2023-06-13",
  "blocks": [
    {
      "blockType": "Header",
      "content": "prova header modifica",
      "order": 1
    },
    {
      "blockType": "Paragrafo",
      "content": "prova paragrafo modifica",
      "order": 2
    }
  ]
}
###

## change title
PUT http://localhost:3001/api/title HTTP/1.1
content-type: application/json

{
  "title": "Content Management system"
}
###

## get the title
GET http://localhost:3001/api/title HTTP/1.1
###

## elimina una pagina se l'utente è loggato
DELETE http://localhost:3001/api/pages/1 HTTP/1.1
###

## get the list of images
GET http://localhost:3001/api/images HTTP/1.1
###

## get an image of the sever
GET http://localhost:3001/images/chatting.webp HTTP/1.1
###

## get the list of users (just id and name)
GET http://localhost:3001/api/users HTTP/1.1
###

